"""
Django settings for prose_example project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "hardcoded-for-development"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# If this project is in debug mode and running on SourceLair, then add
# `localhost` and its Public URL in the allowed hosts.
if DEBUG and os.getenv("SL_PUBLIC_URL"):
    ALLOWED_HOSTS += ["localhost", os.getenv("SL_PUBLIC_URL")]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "prose",
    "blog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "prose.middleware.ProseEditorMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/mnt/media")
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

LOGIN_URL = "blog_login"
LOGIN_REDIRECT_URL = "blog_index"

# Demo-only Lexxy editor chrome (see README: PROSE_EDITOR_THEME).
# Warm off-white canvas and slate-blue accents match the blog header links (#1a5276).
# Applied automatically to every RichTextEditor (article edit, comments).
PROSE_EDITOR_THEME = {
    "background": "#faf8f5",
    "toolbar_background": "#eef4f8",
    "border": "#c5d4de",
    "icon": "#2c5f7a",
    "text": "#1a2e3b",
    "text_subtle": "#5a7386",
    "accent": "#1a5276",
    "focus": "#1a5276",
    "selected": "#e3f0f7",
    "link": "#1a5276",
    "radius": "6px",
}

# Per-field theme overrides for the demo (see article_edit.html {% prose_field %}).
# Keys are passed as theme="…" on the template tag; values merge over PROSE_EDITOR_THEME.
PROSE_EDITOR_FIELD_THEMES = {
    "excerpt": {
        "background": "#f4f8f4",
        "toolbar_background": "#e4ede4",
        "border": "#b8ccb8",
        "icon": "#3d5c3d",
        "text": "#1a2e1a",
        "text_subtle": "#5a735a",
        "accent": "#2d6a2d",
        "focus": "#2d6a2d",
        "selected": "#dceadc",
        "link": "#2d6a2d",
        "radius": "4px",
    },
}
