[tool.poetry]
name = "django-prose"
version = "3.0.0"
description = "Wonderful rich text-editing for Django"
authors = ["Paris Kasidiaris <paris@withlogic.co>"]
license = "MIT"
repository = "https://github.com/withlogicco/django-prose"
readme = "README.md"
packages = [{ include = "prose" }]
include = [
    "prose/templates/**/*",
    "prose/static/**/*",
]

[tool.poetry.dependencies]
python = "^3.8"
django = [
    { version = ">=3.2,<6", python = "<3.12" },
    { version = "6.0.5", python = ">=3.12" },
]
bleach = ">=4.0"
tinycss2 = ">=1.1.0"

[tool.poetry.dev-dependencies]
black = "^24.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
