# Generated by Django 4.1.7 on 2023-02-22 00:57

from django.db import migrations, models
import django.db.models.deletion
import prose.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("prose", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=prose.models.upload_to)),
                ("filename", models.CharField(max_length=120)),
                ("content_type", models.CharField(max_length=120)),
                ("byte_size", models.PositiveIntegerField()),
                ("metadata", models.TextField()),
                (
                    "Document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="prose.document",
                    ),
                ),
            ],
        ),
    ]
