# Generated by Django 4.1.7 on 2023-02-22 01:44

from django.db import migrations, models
import prose.models


class Migration(migrations.Migration):
    dependencies = [
        ("prose", "0002_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="Document",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(editable=False, upload_to=prose.models.upload_to),
        ),
    ]
